### ISSUE TITLE
Practica 4

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [SistemasTecTlaxiaco/practica-de-calculadora-en-consola-y-windows-form-equipohjf#1]
Realizar la consulta de la estructura de una librería e implementa funciones con las librerias en una App de escritorio para entregar un reporte de practica 4 para implementar un libreria en Visual Studio

1. Diseñar el diagrama de clases de una calculadora estándar con las siguientes operaciones.

Sumar
Restar
Multiplicar
Dividir
Raiz Cuadrada
Potencia
Porcentaje
Fracción

2. La implementación del programa principal es en Visual Studio utilizando la consola.
3. 
4. Debe tener un menú principal con la opción de salirse del programa principal.

Una vez entendido el programa que se dio en clase, realizar las modificaciones para realizar en Visual Studio y realizando una Calculadora con botones utilizando Windows Form.

![image](https://user-images.githubusercontent.com/71857813/157727153-d73b9e53-05c7-45bc-b05a-8e60a79925aa.png)

5. La libreria debe compilarse y construirse con atributos, métodos y pases de parámetros.

**Comment by Heidi-19** [comment]
[Uploading Practica 4 - Heidi Lucy Bautista Sanjuan 4US.pdf…]()

**Comment by Heidi-19** [comment]
[Practica 4 - Heidi Lucy Bautista Sanjuan 4US.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-calculadora-en-consola-y-windows-form-equipohjf/files/8239004/Practica.4.-.Heidi.Lucy.Bautista.Sanjuan.4US.pdf)

**Comment by FedericoVictorianoSierra** [comment]
[Practica 4 (Federico Victoriano Sierra (4US)).pdf](https://github.com/SistemasTecTlaxiaco/practica-de-calculadora-en-consola-y-windows-form-equipohjf/files/8239001/Practica.4.Federico.Victoriano.Sierra.4US.pdf)

**Comment by JoseABCruz** [comment]
[Practica 4 - José Antonio Balbuena Cruz 4US.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-calculadora-en-consola-y-windows-form-equipohjf/files/8239754/Practica.4.-.Jose.Antonio.Balbuena.Cruz.4US.pdf)

**Comment by OFELHER93** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
